# Práctica 5: transformación de datos categóricos

## Dataframe 3: Precio de carros usados

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import StandardScaler

In [3]:
df = pd.read_csv('C:/Users/HP/Downloads/train3.csv')

In [4]:
df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

### Transformación de variables numéricas

#### Codificación de un paso (one-hot encoding)

In [6]:
df['Owner_Type'].unique()

array(['First', 'Second', 'Fourth & Above', 'Third'], dtype=object)

In [7]:
pd.get_dummies(df,columns=['Owner_Type'])

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Mileage,Engine,Power,Seats,New_Price,Price,Owner_Type_First,Owner_Type_Fourth & Above,Owner_Type_Second,Owner_Type_Third
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75,1,0,0,0
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,1,0,0,0
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,1,0,0,0
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00,1,0,0,0
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74,0,0,1,0
5,5,Hyundai EON LPG Era Plus Option,Hyderabad,2012,75000,LPG,Manual,21.1 km/kg,814 CC,55.2 bhp,5.0,NaN,2.35,1,0,0,0
6,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,3.50,1,0,0,0
7,7,Toyota Innova Crysta 2.8 GX AT 8S,Mumbai,2016,36000,Diesel,Automatic,11.36 kmpl,2755 CC,171.5 bhp,8.0,21 Lakh,17.50,1,0,0,0
8,8,Volkswagen Vento Diesel Comfortline,Pune,2013,64430,Diesel,Manual,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN,5.20,1,0,0,0
9,9,Tata Indica Vista Quadrajet LS,Chennai,2012,65932,Diesel,Manual,22.3 kmpl,1248 CC,74 bhp,5.0,NaN,1.95,0,0,1,0
10,10,Maruti Ciaz Zeta,Kochi,2018,25692,Petrol,Manual,21.56 kmpl,1462 CC,103.25 bhp,5.0,10.65 Lakh,9.95,1,0,0,0
11,11,Honda City 1.5 V AT Sunroof,Kolkata,2012,60000,Petrol,Automatic,16.8 kmpl,1497 CC,116.3 bhp,5.0,NaN,4.49,1,0,0,0
12,12,Maruti Swift VDI BSIV,Jaipur,2015,64424,Diesel,Manual,25.2 kmpl,1248 CC,74 bhp,5.0,NaN,5.60,1,0,0,0
13,13,Land Rover Range Rover 2.2L Pure,Delhi,2014,72000,Diesel,Automatic,12.7 kmpl,2179 CC,187.7 bhp,5.0,NaN,27.00,1,0,0,0
14,14,Land Rover Freelander 2 TD4 SE,Pune,2012,85000,Diesel,Automatic,0.0 kmpl,2179 CC,115 bhp,5.0,NaN,17.50,0,0,1,0
15,15,Mitsubishi Pajero Sport 4X4,Delhi,2014,110000,Diesel,Manual,13.5 kmpl,2477 CC,175.56 bhp,7.0,32.01 Lakh,15.00,1,0,0,0
16,16,Honda Amaze S i-Dtech,Kochi,2016,58950,Diesel,Manual,25.8 kmpl,1498 CC,98.6 bhp,5.0,NaN,5.40,1,0,0,0
17,17,Maruti Swift DDiS VDI,Jaipur,2017,25000,Diesel,Manual,28.4 kmpl,1248 CC,74 bhp,5.0,NaN,5.99,1,0,0,0
18,18,Renault Duster 85PS Diesel RxL Plus,Kochi,2014,77469,Diesel,Manual,20.45 kmpl,1461 CC,83.8 bhp,5.0,NaN,6.34,1,0,0,0
19,19,Mercedes-Benz New C-Class C 220 CDI BE Avantgare,Bangalore,2014,78500,Diesel,Automatic,14.84 kmpl,2143 CC,167.62 bhp,5.0,NaN,28.00,1,0,0,0
20,20,BMW 3 Series 320d,Kochi,2014,32982,Diesel,Automatic,22.69 kmpl,1995 CC,190 bhp,5.0,47.87 Lakh,18.55,1,0,0,0
21,21,Maruti S Cross DDiS 200 Alpha,Bangalore,2015,55392,Diesel,Manual,23.65 kmpl,1248 CC,88.5 bhp,5.0,NaN,8.25,0,0,1,0
22,22,Audi A6 2011-2015 35 TFSI Technology,Mumbai,2015,55985,Petrol,Automatic,13.53 kmpl,1984 CC,177.01 bhp,5.0,NaN,23.50,1,0,0,0
23,23,Hyundai i20 1.2 Magna,Kolkata,2010,45807,Petrol,Manual,18.5 kmpl,1197 CC,80 bhp,5.0,NaN,1.87,1,0,0,0
24,24,Volkswagen Vento Petrol Highline AT,Kolkata,2010,33000,Petrol,Automatic,14.4 kmpl,1598 CC,103.6 bhp,5.0,NaN,2.85,1,0,0,0
25,25,Honda City Corporate Edition,Mumbai,2012,51920,Petrol,Manual,16.8 kmpl,1497 CC,116.3 bhp,5.0,NaN,4.25,1,0,0,0
26,26,Nissan Micra Diesel XV,Hyderabad,2012,54000,Diesel,Manual,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,4.25,1,0,0,0
27,27,Maruti Alto K10 2010-2014 VXI,Hyderabad,2013,54000,Petrol,Manual,20.92 kmpl,998 CC,67.1 bhp,5.0,NaN,2.75,0,0,1,0
28,28,Honda WRV i-VTEC VX,Kochi,2018,37430,Petrol,Manual,17.5 kmpl,1199 CC,88.7 bhp,5.0,10.57 Lakh,9.90,1,0,0,0
29,29,Toyota Innova 2.5 V Diesel 7-seater,Mumbai,2007,262000,Diesel,Manual,12.8 kmpl,2494 CC,102 bhp,7.0,NaN,4.00,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5989,5989,Audi A4 35 TDI Premium Plus,Coimbatore,2013,58629,Diesel,Automatic,18.25 kmpl,1968 CC,187.74 bhp,5.0,53.14 Lakh,16.52,0,0,1,0
5990,5990,Tata New Safari DICOR 2.2 VX 4x2,Pune,2008,86000,Diesel,Manual,13.93 kmpl,2179 CC,138 bhp,7.0,NaN,0.60,0,0,0,1
5991,5991,Maruti Swift VDI,Hyderabad,2012,68238,Diesel,Manual,22.9 kmpl,1248 CC,74 bhp,5.0,NaN,4.80,1,0,0,0
5992,5992,Skoda Superb Elegance 1.8 TSI AT,Mumbai,2011,42036,Petrol,Automatic,13.7 kmpl,1798 CC,157.75 bhp,5.0,NaN,6.25,1,0,0,0
5993,5993,Hyundai Elantra SX,Mumbai,2014,55619,Petrol,Manual,16.3 kmpl,1797 CC,147.5 bhp,5.0,NaN,8.30,1,0,0,0
5994,5994,Honda City 1.5 E MT,Pune,2009,60000,Petrol,Manual,17.0 kmpl,1497 CC,118 bhp,5.0,NaN,3.25,0,0,0,1
5995,5995,Renault Duster 85PS Diesel RxL Explore,Pune,2015,30000,Diesel,Manual,19.87 kmpl,1461 CC,83.8 bhp,5.0,NaN,7.75,1,0,0,0
5996,5996,Jaguar XF 2.2 Litre Luxury,Kochi,2016,31150,Diesel,Automatic,16.36 kmpl,2179 CC,187.7 bhp,5.0,NaN,30.54,1,0,0,0
5997,5997,Maruti Wagon R Duo Lxi,Jaipur,2010,70000,LPG,Manual,26.2 km/kg,998 CC,58.2 bhp,5.0,NaN,2.27,1,0,0,0
5998,5998,Volkswagen Polo IPL II 1.2 Petrol Highline,Pune,2010,70290,Petrol,Manual,17.24 kmpl,1198 CC,73.9 bhp,5.0,NaN,2.96,0,0,1,0
5999,5999,Tata Bolt Revotron XT,Chennai,2016,10000,Petrol,Manual,17.57 kmpl,1193 CC,88.7 bhp,5.0,7.77 Lakh,4.00,1,0,0,0
6000,6000,Hyundai i20 Sportz 1.2,Bangalore,2014,68010,Petrol,Manual,18.5 kmpl,1197 CC,82.85 bhp,5.0,NaN,5.25,0,0,1,0
6001,6001,Audi A6 2011-2015 2.0 TDI,Kochi,2013,91903,Diesel,Automatic,17.68 kmpl,1968 CC,174.33 bhp,5.0,NaN,17.56,1,0,0,0
6002,6002,Volkswagen Vento 1.6 Highline,Mumbai,2011,38000,Petrol,Manual,16.09 kmpl,1598 CC,103.5 bhp,5.0,11.91 Lakh,3.25,1,0,0,0
6003,6003,Maruti Celerio VXI,Bangalore,2015,67600,Petrol,Manual,23.1 kmpl,998 CC,67.04 bhp,5.0,NaN,4.00,1,0,0,0
6004,6004,Hyundai Getz GLE,Coimbatore,2007,66800,Petrol,Manual,15.3 kmpl,1341 CC,83 bhp,5.0,NaN,2.20,1,0,0,0
6005,6005,Maruti Vitara Brezza VDi,Pune,2016,37208,Diesel,Manual,24.3 kmpl,1248 CC,88.5 bhp,5.0,9.93 Lakh,7.43,1,0,0,0
6006,6006,Mercedes-Benz M-Class ML 320 CDI,Mumbai,2009,102002,Diesel,Automatic,8.7 kmpl,2987 CC,224.34 bhp,5.0,NaN,10.75,1,0,0,0
6007,6007,Maruti Swift Dzire Vdi BSIV,Delhi,2011,68000,Diesel,Manual,19.3 kmpl,1248 CC,73.9 bhp,5.0,NaN,2.75,1,0,0,0
6008,6008,Porsche Panamera Diesel,Hyderabad,2013,40000,Diesel,Automatic,17.85 kmpl,2967 CC,300 bhp,4.0,NaN,45.00,0,0,1,0
6009,6009,Toyota Camry Hybrid,Mumbai,2015,33500,Petrol,Automatic,19.16 kmpl,2494 CC,158.2 bhp,5.0,NaN,19.75,1,0,0,0
6010,6010,Honda Brio 1.2 VX MT,Delhi,2013,33746,Petrol,Manual,18.5 kmpl,1198 CC,86.8 bhp,5.0,6.63 Lakh,3.20,1,0,0,0
6011,6011,Skoda Superb 3.6 V6 FSI,Hyderabad,2009,53000,Petrol,Automatic,0.0 kmpl,3597 CC,262.6 bhp,5.0,NaN,4.75,1,0,0,0
6012,6012,Toyota Innova 2.5 V Diesel 7-seater,Coimbatore,2011,45004,Diesel,Manual,12.8 kmpl,2494 CC,102 bhp,7.0,NaN,9.48,1,0,0,0
6013,6013,Honda Amaze VX i-DTEC,Coimbatore,2015,70602,Diesel,Manual,25.8 kmpl,1498 CC,98.6 bhp,5.0,NaN,4.83,1,0,0,0
6014,6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,28.4 kmpl,1248 CC,74 bhp,5.0,7.88 Lakh,4.75,1,0,0,0
6015,6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,24.4 kmpl,1120 CC,71 bhp,5.0,NaN,4.00,1,0,0,0
6016,6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,14.0 kmpl,2498 CC,112 bhp,8.0,NaN,2.90,0,0,1,0
6017,6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,18.9 kmpl,998 CC,67.1 bhp,5.0,NaN,2.65,1,0,0,0
6018,6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,25.44 kmpl,936 CC,57.6 bhp,5.0,NaN,2.50,1,0,0,0

#### Codificación de etiquetas (label encoding)

In [9]:
from sklearn.preprocessing import LabelEncoder

In [10]:
le = LabelEncoder()
le.fit(df['Owner_Type'])
df['Owner_Type_le'] = le.transform(df['Owner_Type'])
df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Owner_Type_le
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75,0
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,0
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,0
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00,0
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74,2

#### Feature hash

In [11]:
from sklearn.feature_extraction import FeatureHasher

In [12]:
fh = FeatureHasher(n_features=3, input_type='string')
hashed = fh.transform(df[['Owner_Type']].astype(str).values)
hashed = pd.DataFrame(hashed.todense())
hashed.head()

     0    1    2
0  0.0  0.0  1.0
1  0.0  0.0  1.0
2  0.0  0.0  1.0
3  0.0  0.0  1.0
4  0.0  1.0  0.0

In [13]:
hashed.columns = ['Owner_Type_fh' + str(i) for i in hashed.columns]
pd.concat([df, hashed], axis=1)

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Owner_Type_le,Owner_Type_fh0,Owner_Type_fh1,Owner_Type_fh2
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75,0,0.0,0.0,1.0
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,0,0.0,0.0,1.0
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,0,0.0,0.0,1.0
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00,0,0.0,0.0,1.0
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74,2,0.0,1.0,0.0
5,5,Hyundai EON LPG Era Plus Option,Hyderabad,2012,75000,LPG,Manual,First,21.1 km/kg,814 CC,55.2 bhp,5.0,NaN,2.35,0,0.0,0.0,1.0
6,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,3.50,0,0.0,0.0,1.0
7,7,Toyota Innova Crysta 2.8 GX AT 8S,Mumbai,2016,36000,Diesel,Automatic,First,11.36 kmpl,2755 CC,171.5 bhp,8.0,21 Lakh,17.50,0,0.0,0.0,1.0
8,8,Volkswagen Vento Diesel Comfortline,Pune,2013,64430,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN,5.20,0,0.0,0.0,1.0
9,9,Tata Indica Vista Quadrajet LS,Chennai,2012,65932,Diesel,Manual,Second,22.3 kmpl,1248 CC,74 bhp,5.0,NaN,1.95,2,0.0,1.0,0.0
10,10,Maruti Ciaz Zeta,Kochi,2018,25692,Petrol,Manual,First,21.56 kmpl,1462 CC,103.25 bhp,5.0,10.65 Lakh,9.95,0,0.0,0.0,1.0
11,11,Honda City 1.5 V AT Sunroof,Kolkata,2012,60000,Petrol,Automatic,First,16.8 kmpl,1497 CC,116.3 bhp,5.0,NaN,4.49,0,0.0,0.0,1.0
12,12,Maruti Swift VDI BSIV,Jaipur,2015,64424,Diesel,Manual,First,25.2 kmpl,1248 CC,74 bhp,5.0,NaN,5.60,0,0.0,0.0,1.0
13,13,Land Rover Range Rover 2.2L Pure,Delhi,2014,72000,Diesel,Automatic,First,12.7 kmpl,2179 CC,187.7 bhp,5.0,NaN,27.00,0,0.0,0.0,1.0
14,14,Land Rover Freelander 2 TD4 SE,Pune,2012,85000,Diesel,Automatic,Second,0.0 kmpl,2179 CC,115 bhp,5.0,NaN,17.50,2,0.0,1.0,0.0
15,15,Mitsubishi Pajero Sport 4X4,Delhi,2014,110000,Diesel,Manual,First,13.5 kmpl,2477 CC,175.56 bhp,7.0,32.01 Lakh,15.00,0,0.0,0.0,1.0
16,16,Honda Amaze S i-Dtech,Kochi,2016,58950,Diesel,Manual,First,25.8 kmpl,1498 CC,98.6 bhp,5.0,NaN,5.40,0,0.0,0.0,1.0
17,17,Maruti Swift DDiS VDI,Jaipur,2017,25000,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5.0,NaN,5.99,0,0.0,0.0,1.0
18,18,Renault Duster 85PS Diesel RxL Plus,Kochi,2014,77469,Diesel,Manual,First,20.45 kmpl,1461 CC,83.8 bhp,5.0,NaN,6.34,0,0.0,0.0,1.0
19,19,Mercedes-Benz New C-Class C 220 CDI BE Avantgare,Bangalore,2014,78500,Diesel,Automatic,First,14.84 kmpl,2143 CC,167.62 bhp,5.0,NaN,28.00,0,0.0,0.0,1.0
20,20,BMW 3 Series 320d,Kochi,2014,32982,Diesel,Automatic,First,22.69 kmpl,1995 CC,190 bhp,5.0,47.87 Lakh,18.55,0,0.0,0.0,1.0
21,21,Maruti S Cross DDiS 200 Alpha,Bangalore,2015,55392,Diesel,Manual,Second,23.65 kmpl,1248 CC,88.5 bhp,5.0,NaN,8.25,2,0.0,1.0,0.0
22,22,Audi A6 2011-2015 35 TFSI Technology,Mumbai,2015,55985,Petrol,Automatic,First,13.53 kmpl,1984 CC,177.01 bhp,5.0,NaN,23.50,0,0.0,0.0,1.0
23,23,Hyundai i20 1.2 Magna,Kolkata,2010,45807,Petrol,Manual,First,18.5 kmpl,1197 CC,80 bhp,5.0,NaN,1.87,0,0.0,0.0,1.0
24,24,Volkswagen Vento Petrol Highline AT,Kolkata,2010,33000,Petrol,Automatic,First,14.4 kmpl,1598 CC,103.6 bhp,5.0,NaN,2.85,0,0.0,0.0,1.0
25,25,Honda City Corporate Edition,Mumbai,2012,51920,Petrol,Manual,First,16.8 kmpl,1497 CC,116.3 bhp,5.0,NaN,4.25,0,0.0,0.0,1.0
26,26,Nissan Micra Diesel XV,Hyderabad,2012,54000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,4.25,0,0.0,0.0,1.0
27,27,Maruti Alto K10 2010-2014 VXI,Hyderabad,2013,54000,Petrol,Manual,Second,20.92 kmpl,998 CC,67.1 bhp,5.0,NaN,2.75,2,0.0,1.0,0.0
28,28,Honda WRV i-VTEC VX,Kochi,2018,37430,Petrol,Manual,First,17.5 kmpl,1199 CC,88.7 bhp,5.0,10.57 Lakh,9.90,0,0.0,0.0,1.0
29,29,Toyota Innova 2.5 V Diesel 7-seater,Mumbai,2007,262000,Diesel,Manual,Fourth & Above,12.8 kmpl,2494 CC,102 bhp,7.0,NaN,4.00,1,0.0,-1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5989,5989,Audi A4 35 TDI Premium Plus,Coimbatore,2013,58629,Diesel,Automatic,Second,18.25 kmpl,1968 CC,187.74 bhp,5.0,53.14 Lakh,16.52,2,0.0,1.0,0.0
5990,5990,Tata New Safari DICOR 2.2 VX 4x2,Pune,2008,86000,Diesel,Manual,Third,13.93 kmpl,2179 CC,138 bhp,7.0,NaN,0.60,3,0.0,1.0,0.0
5991,5991,Maruti Swift VDI,Hyderabad,2012,68238,Diesel,Manual,First,22.9 kmpl,1248 CC,74 bhp,5.0,NaN,4.80,0,0.0,0.0,1.0
5992,5992,Skoda Superb Elegance 1.8 TSI AT,Mumbai,2011,42036,Petrol,Automatic,First,13.7 kmpl,1798 CC,157.75 bhp,5.0,NaN,6.25,0,0.0,0.0,1.0
5993,5993,Hyundai Elantra SX,Mumbai,2014,55619,Petrol,Manual,First,16.3 kmpl,1797 CC,147.5 bhp,5.0,NaN,8.30,0,0.0,0.0,1.0
5994,5994,Honda City 1.5 E MT,Pune,2009,60000,Petrol,Manual,Third,17.0 kmpl,1497 CC,118 bhp,5.0,NaN,3.25,3,0.0,1.0,0.0
5995,5995,Renault Duster 85PS Diesel RxL Explore,Pune,2015,30000,Diesel,Manual,First,19.87 kmpl,1461 CC,83.8 bhp,5.0,NaN,7.75,0,0.0,0.0,1.0
5996,5996,Jaguar XF 2.2 Litre Luxury,Kochi,2016,31150,Diesel,Automatic,First,16.36 kmpl,2179 CC,187.7 bhp,5.0,NaN,30.54,0,0.0,0.0,1.0
5997,5997,Maruti Wagon R Duo Lxi,Jaipur,2010,70000,LPG,Manual,First,26.2 km/kg,998 CC,58.2 bhp,5.0,NaN,2.27,0,0.0,0.0,1.0
5998,5998,Volkswagen Polo IPL II 1.2 Petrol Highline,Pune,2010,70290,Petrol,Manual,Second,17.24 kmpl,1198 CC,73.9 bhp,5.0,NaN,2.96,2,0.0,1.0,0.0
5999,5999,Tata Bolt Revotron XT,Chennai,2016,10000,Petrol,Manual,First,17.57 kmpl,1193 CC,88.7 bhp,5.0,7.77 Lakh,4.00,0,0.0,0.0,1.0
6000,6000,Hyundai i20 Sportz 1.2,Bangalore,2014,68010,Petrol,Manual,Second,18.5 kmpl,1197 CC,82.85 bhp,5.0,NaN,5.25,2,0.0,1.0,0.0
6001,6001,Audi A6 2011-2015 2.0 TDI,Kochi,2013,91903,Diesel,Automatic,First,17.68 kmpl,1968 CC,174.33 bhp,5.0,NaN,17.56,0,0.0,0.0,1.0
6002,6002,Volkswagen Vento 1.6 Highline,Mumbai,2011,38000,Petrol,Manual,First,16.09 kmpl,1598 CC,103.5 bhp,5.0,11.91 Lakh,3.25,0,0.0,0.0,1.0
6003,6003,Maruti Celerio VXI,Bangalore,2015,67600,Petrol,Manual,First,23.1 kmpl,998 CC,67.04 bhp,5.0,NaN,4.00,0,0.0,0.0,1.0
6004,6004,Hyundai Getz GLE,Coimbatore,2007,66800,Petrol,Manual,First,15.3 kmpl,1341 CC,83 bhp,5.0,NaN,2.20,0,0.0,0.0,1.0
6005,6005,Maruti Vitara Brezza VDi,Pune,2016,37208,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,9.93 Lakh,7.43,0,0.0,0.0,1.0
6006,6006,Mercedes-Benz M-Class ML 320 CDI,Mumbai,2009,102002,Diesel,Automatic,First,8.7 kmpl,2987 CC,224.34 bhp,5.0,NaN,10.75,0,0.0,0.0,1.0
6007,6007,Maruti Swift Dzire Vdi BSIV,Delhi,2011,68000,Diesel,Manual,First,19.3 kmpl,1248 CC,73.9 bhp,5.0,NaN,2.75,0,0.0,0.0,1.0
6008,6008,Porsche Panamera Diesel,Hyderabad,2013,40000,Diesel,Automatic,Second,17.85 kmpl,2967 CC,300 bhp,4.0,NaN,45.00,2,0.0,1.0,0.0
6009,6009,Toyota Camry Hybrid,Mumbai,2015,33500,Petrol,Automatic,First,19.16 kmpl,2494 CC,158.2 bhp,5.0,NaN,19.75,0,0.0,0.0,1.0
6010,6010,Honda Brio 1.2 VX MT,Delhi,2013,33746,Petrol,Manual,First,18.5 kmpl,1198 CC,86.8 bhp,5.0,6.63 Lakh,3.20,0,0.0,0.0,1.0
6011,6011,Skoda Superb 3.6 V6 FSI,Hyderabad,2009,53000,Petrol,Automatic,First,0.0 kmpl,3597 CC,262.6 bhp,5.0,NaN,4.75,0,0.0,0.0,1.0
6012,6012,Toyota Innova 2.5 V Diesel 7-seater,Coimbatore,2011,45004,Diesel,Manual,First,12.8 kmpl,2494 CC,102 bhp,7.0,NaN,9.48,0,0.0,0.0,1.0
6013,6013,Honda Amaze VX i-DTEC,Coimbatore,2015,70602,Diesel,Manual,First,25.8 kmpl,1498 CC,98.6 bhp,5.0,NaN,4.83,0,0.0,0.0,1.0
6014,6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5.0,7.88 Lakh,4.75,0,0.0,0.0,1.0
6015,6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.4 kmpl,1120 CC,71 bhp,5.0,NaN,4.00,0,0.0,0.0,1.0
6016,6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.0 kmpl,2498 CC,112 bhp,8.0,NaN,2.90,2,0.0,1.0,0.0
6017,6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.9 kmpl,998 CC,67.1 bhp,5.0,NaN,2.65,0,0.0,0.0,1.0
6018,6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44 kmpl,936 CC,57.6 bhp,5.0,NaN,2.50,0,0.0,0.0,1.0

#### Codificación binaria

In [14]:
from category_encoders import BinaryEncoder


be = BinaryEncoder()
df_be = be.fit_transform(df['Owner_Type'])
pd.concat([df,df_be],axis=1)

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Owner_Type_le,Owner_Type_0,Owner_Type_1,Owner_Type_2
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75,0,0,0,1
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,0,0,0,1
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,0,0,0,1
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00,0,0,0,1
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74,2,0,1,0
5,5,Hyundai EON LPG Era Plus Option,Hyderabad,2012,75000,LPG,Manual,First,21.1 km/kg,814 CC,55.2 bhp,5.0,NaN,2.35,0,0,0,1
6,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,3.50,0,0,0,1
7,7,Toyota Innova Crysta 2.8 GX AT 8S,Mumbai,2016,36000,Diesel,Automatic,First,11.36 kmpl,2755 CC,171.5 bhp,8.0,21 Lakh,17.50,0,0,0,1
8,8,Volkswagen Vento Diesel Comfortline,Pune,2013,64430,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN,5.20,0,0,0,1
9,9,Tata Indica Vista Quadrajet LS,Chennai,2012,65932,Diesel,Manual,Second,22.3 kmpl,1248 CC,74 bhp,5.0,NaN,1.95,2,0,1,0
10,10,Maruti Ciaz Zeta,Kochi,2018,25692,Petrol,Manual,First,21.56 kmpl,1462 CC,103.25 bhp,5.0,10.65 Lakh,9.95,0,0,0,1
11,11,Honda City 1.5 V AT Sunroof,Kolkata,2012,60000,Petrol,Automatic,First,16.8 kmpl,1497 CC,116.3 bhp,5.0,NaN,4.49,0,0,0,1
12,12,Maruti Swift VDI BSIV,Jaipur,2015,64424,Diesel,Manual,First,25.2 kmpl,1248 CC,74 bhp,5.0,NaN,5.60,0,0,0,1
13,13,Land Rover Range Rover 2.2L Pure,Delhi,2014,72000,Diesel,Automatic,First,12.7 kmpl,2179 CC,187.7 bhp,5.0,NaN,27.00,0,0,0,1
14,14,Land Rover Freelander 2 TD4 SE,Pune,2012,85000,Diesel,Automatic,Second,0.0 kmpl,2179 CC,115 bhp,5.0,NaN,17.50,2,0,1,0
15,15,Mitsubishi Pajero Sport 4X4,Delhi,2014,110000,Diesel,Manual,First,13.5 kmpl,2477 CC,175.56 bhp,7.0,32.01 Lakh,15.00,0,0,0,1
16,16,Honda Amaze S i-Dtech,Kochi,2016,58950,Diesel,Manual,First,25.8 kmpl,1498 CC,98.6 bhp,5.0,NaN,5.40,0,0,0,1
17,17,Maruti Swift DDiS VDI,Jaipur,2017,25000,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5.0,NaN,5.99,0,0,0,1
18,18,Renault Duster 85PS Diesel RxL Plus,Kochi,2014,77469,Diesel,Manual,First,20.45 kmpl,1461 CC,83.8 bhp,5.0,NaN,6.34,0,0,0,1
19,19,Mercedes-Benz New C-Class C 220 CDI BE Avantgare,Bangalore,2014,78500,Diesel,Automatic,First,14.84 kmpl,2143 CC,167.62 bhp,5.0,NaN,28.00,0,0,0,1
20,20,BMW 3 Series 320d,Kochi,2014,32982,Diesel,Automatic,First,22.69 kmpl,1995 CC,190 bhp,5.0,47.87 Lakh,18.55,0,0,0,1
21,21,Maruti S Cross DDiS 200 Alpha,Bangalore,2015,55392,Diesel,Manual,Second,23.65 kmpl,1248 CC,88.5 bhp,5.0,NaN,8.25,2,0,1,0
22,22,Audi A6 2011-2015 35 TFSI Technology,Mumbai,2015,55985,Petrol,Automatic,First,13.53 kmpl,1984 CC,177.01 bhp,5.0,NaN,23.50,0,0,0,1
23,23,Hyundai i20 1.2 Magna,Kolkata,2010,45807,Petrol,Manual,First,18.5 kmpl,1197 CC,80 bhp,5.0,NaN,1.87,0,0,0,1
24,24,Volkswagen Vento Petrol Highline AT,Kolkata,2010,33000,Petrol,Automatic,First,14.4 kmpl,1598 CC,103.6 bhp,5.0,NaN,2.85,0,0,0,1
25,25,Honda City Corporate Edition,Mumbai,2012,51920,Petrol,Manual,First,16.8 kmpl,1497 CC,116.3 bhp,5.0,NaN,4.25,0,0,0,1
26,26,Nissan Micra Diesel XV,Hyderabad,2012,54000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,4.25,0,0,0,1
27,27,Maruti Alto K10 2010-2014 VXI,Hyderabad,2013,54000,Petrol,Manual,Second,20.92 kmpl,998 CC,67.1 bhp,5.0,NaN,2.75,2,0,1,0
28,28,Honda WRV i-VTEC VX,Kochi,2018,37430,Petrol,Manual,First,17.5 kmpl,1199 CC,88.7 bhp,5.0,10.57 Lakh,9.90,0,0,0,1
29,29,Toyota Innova 2.5 V Diesel 7-seater,Mumbai,2007,262000,Diesel,Manual,Fourth & Above,12.8 kmpl,2494 CC,102 bhp,7.0,NaN,4.00,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5989,5989,Audi A4 35 TDI Premium Plus,Coimbatore,2013,58629,Diesel,Automatic,Second,18.25 kmpl,1968 CC,187.74 bhp,5.0,53.14 Lakh,16.52,2,0,1,0
5990,5990,Tata New Safari DICOR 2.2 VX 4x2,Pune,2008,86000,Diesel,Manual,Third,13.93 kmpl,2179 CC,138 bhp,7.0,NaN,0.60,3,1,0,0
5991,5991,Maruti Swift VDI,Hyderabad,2012,68238,Diesel,Manual,First,22.9 kmpl,1248 CC,74 bhp,5.0,NaN,4.80,0,0,0,1
5992,5992,Skoda Superb Elegance 1.8 TSI AT,Mumbai,2011,42036,Petrol,Automatic,First,13.7 kmpl,1798 CC,157.75 bhp,5.0,NaN,6.25,0,0,0,1
5993,5993,Hyundai Elantra SX,Mumbai,2014,55619,Petrol,Manual,First,16.3 kmpl,1797 CC,147.5 bhp,5.0,NaN,8.30,0,0,0,1
5994,5994,Honda City 1.5 E MT,Pune,2009,60000,Petrol,Manual,Third,17.0 kmpl,1497 CC,118 bhp,5.0,NaN,3.25,3,1,0,0
5995,5995,Renault Duster 85PS Diesel RxL Explore,Pune,2015,30000,Diesel,Manual,First,19.87 kmpl,1461 CC,83.8 bhp,5.0,NaN,7.75,0,0,0,1
5996,5996,Jaguar XF 2.2 Litre Luxury,Kochi,2016,31150,Diesel,Automatic,First,16.36 kmpl,2179 CC,187.7 bhp,5.0,NaN,30.54,0,0,0,1
5997,5997,Maruti Wagon R Duo Lxi,Jaipur,2010,70000,LPG,Manual,First,26.2 km/kg,998 CC,58.2 bhp,5.0,NaN,2.27,0,0,0,1
5998,5998,Volkswagen Polo IPL II 1.2 Petrol Highline,Pune,2010,70290,Petrol,Manual,Second,17.24 kmpl,1198 CC,73.9 bhp,5.0,NaN,2.96,2,0,1,0
5999,5999,Tata Bolt Revotron XT,Chennai,2016,10000,Petrol,Manual,First,17.57 kmpl,1193 CC,88.7 bhp,5.0,7.77 Lakh,4.00,0,0,0,1
6000,6000,Hyundai i20 Sportz 1.2,Bangalore,2014,68010,Petrol,Manual,Second,18.5 kmpl,1197 CC,82.85 bhp,5.0,NaN,5.25,2,0,1,0
6001,6001,Audi A6 2011-2015 2.0 TDI,Kochi,2013,91903,Diesel,Automatic,First,17.68 kmpl,1968 CC,174.33 bhp,5.0,NaN,17.56,0,0,0,1
6002,6002,Volkswagen Vento 1.6 Highline,Mumbai,2011,38000,Petrol,Manual,First,16.09 kmpl,1598 CC,103.5 bhp,5.0,11.91 Lakh,3.25,0,0,0,1
6003,6003,Maruti Celerio VXI,Bangalore,2015,67600,Petrol,Manual,First,23.1 kmpl,998 CC,67.04 bhp,5.0,NaN,4.00,0,0,0,1
6004,6004,Hyundai Getz GLE,Coimbatore,2007,66800,Petrol,Manual,First,15.3 kmpl,1341 CC,83 bhp,5.0,NaN,2.20,0,0,0,1
6005,6005,Maruti Vitara Brezza VDi,Pune,2016,37208,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,9.93 Lakh,7.43,0,0,0,1
6006,6006,Mercedes-Benz M-Class ML 320 CDI,Mumbai,2009,102002,Diesel,Automatic,First,8.7 kmpl,2987 CC,224.34 bhp,5.0,NaN,10.75,0,0,0,1
6007,6007,Maruti Swift Dzire Vdi BSIV,Delhi,2011,68000,Diesel,Manual,First,19.3 kmpl,1248 CC,73.9 bhp,5.0,NaN,2.75,0,0,0,1
6008,6008,Porsche Panamera Diesel,Hyderabad,2013,40000,Diesel,Automatic,Second,17.85 kmpl,2967 CC,300 bhp,4.0,NaN,45.00,2,0,1,0
6009,6009,Toyota Camry Hybrid,Mumbai,2015,33500,Petrol,Automatic,First,19.16 kmpl,2494 CC,158.2 bhp,5.0,NaN,19.75,0,0,0,1
6010,6010,Honda Brio 1.2 VX MT,Delhi,2013,33746,Petrol,Manual,First,18.5 kmpl,1198 CC,86.8 bhp,5.0,6.63 Lakh,3.20,0,0,0,1
6011,6011,Skoda Superb 3.6 V6 FSI,Hyderabad,2009,53000,Petrol,Automatic,First,0.0 kmpl,3597 CC,262.6 bhp,5.0,NaN,4.75,0,0,0,1
6012,6012,Toyota Innova 2.5 V Diesel 7-seater,Coimbatore,2011,45004,Diesel,Manual,First,12.8 kmpl,2494 CC,102 bhp,7.0,NaN,9.48,0,0,0,1
6013,6013,Honda Amaze VX i-DTEC,Coimbatore,2015,70602,Diesel,Manual,First,25.8 kmpl,1498 CC,98.6 bhp,5.0,NaN,4.83,0,0,0,1
6014,6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5.0,7.88 Lakh,4.75,0,0,0,1
6015,6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.4 kmpl,1120 CC,71 bhp,5.0,NaN,4.00,0,0,0,1
6016,6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.0 kmpl,2498 CC,112 bhp,8.0,NaN,2.90,2,0,1,0
6017,6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.9 kmpl,998 CC,67.1 bhp,5.0,NaN,2.65,0,0,0,1
6018,6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44 kmpl,936 CC,57.6 bhp,5.0,NaN,2.50,0,0,0,1

#### Codificación Base N

In [15]:
from category_encoders import BaseNEncoder

bne = BaseNEncoder(base=3)
df_bne = bne.fit_transform(df['Owner_Type'])
pd.concat([df, df_bne],axis=1)

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Owner_Type_le,Owner_Type_0,Owner_Type_1,Owner_Type_2
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75,0,0,0,1
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,0,0,0,1
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,0,0,0,1
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00,0,0,0,1
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74,2,0,0,2
5,5,Hyundai EON LPG Era Plus Option,Hyderabad,2012,75000,LPG,Manual,First,21.1 km/kg,814 CC,55.2 bhp,5.0,NaN,2.35,0,0,0,1
6,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,3.50,0,0,0,1
7,7,Toyota Innova Crysta 2.8 GX AT 8S,Mumbai,2016,36000,Diesel,Automatic,First,11.36 kmpl,2755 CC,171.5 bhp,8.0,21 Lakh,17.50,0,0,0,1
8,8,Volkswagen Vento Diesel Comfortline,Pune,2013,64430,Diesel,Manual,First,20.54 kmpl,1598 CC,103.6 bhp,5.0,NaN,5.20,0,0,0,1
9,9,Tata Indica Vista Quadrajet LS,Chennai,2012,65932,Diesel,Manual,Second,22.3 kmpl,1248 CC,74 bhp,5.0,NaN,1.95,2,0,0,2
10,10,Maruti Ciaz Zeta,Kochi,2018,25692,Petrol,Manual,First,21.56 kmpl,1462 CC,103.25 bhp,5.0,10.65 Lakh,9.95,0,0,0,1
11,11,Honda City 1.5 V AT Sunroof,Kolkata,2012,60000,Petrol,Automatic,First,16.8 kmpl,1497 CC,116.3 bhp,5.0,NaN,4.49,0,0,0,1
12,12,Maruti Swift VDI BSIV,Jaipur,2015,64424,Diesel,Manual,First,25.2 kmpl,1248 CC,74 bhp,5.0,NaN,5.60,0,0,0,1
13,13,Land Rover Range Rover 2.2L Pure,Delhi,2014,72000,Diesel,Automatic,First,12.7 kmpl,2179 CC,187.7 bhp,5.0,NaN,27.00,0,0,0,1
14,14,Land Rover Freelander 2 TD4 SE,Pune,2012,85000,Diesel,Automatic,Second,0.0 kmpl,2179 CC,115 bhp,5.0,NaN,17.50,2,0,0,2
15,15,Mitsubishi Pajero Sport 4X4,Delhi,2014,110000,Diesel,Manual,First,13.5 kmpl,2477 CC,175.56 bhp,7.0,32.01 Lakh,15.00,0,0,0,1
16,16,Honda Amaze S i-Dtech,Kochi,2016,58950,Diesel,Manual,First,25.8 kmpl,1498 CC,98.6 bhp,5.0,NaN,5.40,0,0,0,1
17,17,Maruti Swift DDiS VDI,Jaipur,2017,25000,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5.0,NaN,5.99,0,0,0,1
18,18,Renault Duster 85PS Diesel RxL Plus,Kochi,2014,77469,Diesel,Manual,First,20.45 kmpl,1461 CC,83.8 bhp,5.0,NaN,6.34,0,0,0,1
19,19,Mercedes-Benz New C-Class C 220 CDI BE Avantgare,Bangalore,2014,78500,Diesel,Automatic,First,14.84 kmpl,2143 CC,167.62 bhp,5.0,NaN,28.00,0,0,0,1
20,20,BMW 3 Series 320d,Kochi,2014,32982,Diesel,Automatic,First,22.69 kmpl,1995 CC,190 bhp,5.0,47.87 Lakh,18.55,0,0,0,1
21,21,Maruti S Cross DDiS 200 Alpha,Bangalore,2015,55392,Diesel,Manual,Second,23.65 kmpl,1248 CC,88.5 bhp,5.0,NaN,8.25,2,0,0,2
22,22,Audi A6 2011-2015 35 TFSI Technology,Mumbai,2015,55985,Petrol,Automatic,First,13.53 kmpl,1984 CC,177.01 bhp,5.0,NaN,23.50,0,0,0,1
23,23,Hyundai i20 1.2 Magna,Kolkata,2010,45807,Petrol,Manual,First,18.5 kmpl,1197 CC,80 bhp,5.0,NaN,1.87,0,0,0,1
24,24,Volkswagen Vento Petrol Highline AT,Kolkata,2010,33000,Petrol,Automatic,First,14.4 kmpl,1598 CC,103.6 bhp,5.0,NaN,2.85,0,0,0,1
25,25,Honda City Corporate Edition,Mumbai,2012,51920,Petrol,Manual,First,16.8 kmpl,1497 CC,116.3 bhp,5.0,NaN,4.25,0,0,0,1
26,26,Nissan Micra Diesel XV,Hyderabad,2012,54000,Diesel,Manual,First,23.08 kmpl,1461 CC,63.1 bhp,5.0,NaN,4.25,0,0,0,1
27,27,Maruti Alto K10 2010-2014 VXI,Hyderabad,2013,54000,Petrol,Manual,Second,20.92 kmpl,998 CC,67.1 bhp,5.0,NaN,2.75,2,0,0,2
28,28,Honda WRV i-VTEC VX,Kochi,2018,37430,Petrol,Manual,First,17.5 kmpl,1199 CC,88.7 bhp,5.0,10.57 Lakh,9.90,0,0,0,1
29,29,Toyota Innova 2.5 V Diesel 7-seater,Mumbai,2007,262000,Diesel,Manual,Fourth & Above,12.8 kmpl,2494 CC,102 bhp,7.0,NaN,4.00,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5989,5989,Audi A4 35 TDI Premium Plus,Coimbatore,2013,58629,Diesel,Automatic,Second,18.25 kmpl,1968 CC,187.74 bhp,5.0,53.14 Lakh,16.52,2,0,0,2
5990,5990,Tata New Safari DICOR 2.2 VX 4x2,Pune,2008,86000,Diesel,Manual,Third,13.93 kmpl,2179 CC,138 bhp,7.0,NaN,0.60,3,0,1,1
5991,5991,Maruti Swift VDI,Hyderabad,2012,68238,Diesel,Manual,First,22.9 kmpl,1248 CC,74 bhp,5.0,NaN,4.80,0,0,0,1
5992,5992,Skoda Superb Elegance 1.8 TSI AT,Mumbai,2011,42036,Petrol,Automatic,First,13.7 kmpl,1798 CC,157.75 bhp,5.0,NaN,6.25,0,0,0,1
5993,5993,Hyundai Elantra SX,Mumbai,2014,55619,Petrol,Manual,First,16.3 kmpl,1797 CC,147.5 bhp,5.0,NaN,8.30,0,0,0,1
5994,5994,Honda City 1.5 E MT,Pune,2009,60000,Petrol,Manual,Third,17.0 kmpl,1497 CC,118 bhp,5.0,NaN,3.25,3,0,1,1
5995,5995,Renault Duster 85PS Diesel RxL Explore,Pune,2015,30000,Diesel,Manual,First,19.87 kmpl,1461 CC,83.8 bhp,5.0,NaN,7.75,0,0,0,1
5996,5996,Jaguar XF 2.2 Litre Luxury,Kochi,2016,31150,Diesel,Automatic,First,16.36 kmpl,2179 CC,187.7 bhp,5.0,NaN,30.54,0,0,0,1
5997,5997,Maruti Wagon R Duo Lxi,Jaipur,2010,70000,LPG,Manual,First,26.2 km/kg,998 CC,58.2 bhp,5.0,NaN,2.27,0,0,0,1
5998,5998,Volkswagen Polo IPL II 1.2 Petrol Highline,Pune,2010,70290,Petrol,Manual,Second,17.24 kmpl,1198 CC,73.9 bhp,5.0,NaN,2.96,2,0,0,2
5999,5999,Tata Bolt Revotron XT,Chennai,2016,10000,Petrol,Manual,First,17.57 kmpl,1193 CC,88.7 bhp,5.0,7.77 Lakh,4.00,0,0,0,1
6000,6000,Hyundai i20 Sportz 1.2,Bangalore,2014,68010,Petrol,Manual,Second,18.5 kmpl,1197 CC,82.85 bhp,5.0,NaN,5.25,2,0,0,2
6001,6001,Audi A6 2011-2015 2.0 TDI,Kochi,2013,91903,Diesel,Automatic,First,17.68 kmpl,1968 CC,174.33 bhp,5.0,NaN,17.56,0,0,0,1
6002,6002,Volkswagen Vento 1.6 Highline,Mumbai,2011,38000,Petrol,Manual,First,16.09 kmpl,1598 CC,103.5 bhp,5.0,11.91 Lakh,3.25,0,0,0,1
6003,6003,Maruti Celerio VXI,Bangalore,2015,67600,Petrol,Manual,First,23.1 kmpl,998 CC,67.04 bhp,5.0,NaN,4.00,0,0,0,1
6004,6004,Hyundai Getz GLE,Coimbatore,2007,66800,Petrol,Manual,First,15.3 kmpl,1341 CC,83 bhp,5.0,NaN,2.20,0,0,0,1
6005,6005,Maruti Vitara Brezza VDi,Pune,2016,37208,Diesel,Manual,First,24.3 kmpl,1248 CC,88.5 bhp,5.0,9.93 Lakh,7.43,0,0,0,1
6006,6006,Mercedes-Benz M-Class ML 320 CDI,Mumbai,2009,102002,Diesel,Automatic,First,8.7 kmpl,2987 CC,224.34 bhp,5.0,NaN,10.75,0,0,0,1
6007,6007,Maruti Swift Dzire Vdi BSIV,Delhi,2011,68000,Diesel,Manual,First,19.3 kmpl,1248 CC,73.9 bhp,5.0,NaN,2.75,0,0,0,1
6008,6008,Porsche Panamera Diesel,Hyderabad,2013,40000,Diesel,Automatic,Second,17.85 kmpl,2967 CC,300 bhp,4.0,NaN,45.00,2,0,0,2
6009,6009,Toyota Camry Hybrid,Mumbai,2015,33500,Petrol,Automatic,First,19.16 kmpl,2494 CC,158.2 bhp,5.0,NaN,19.75,0,0,0,1
6010,6010,Honda Brio 1.2 VX MT,Delhi,2013,33746,Petrol,Manual,First,18.5 kmpl,1198 CC,86.8 bhp,5.0,6.63 Lakh,3.20,0,0,0,1
6011,6011,Skoda Superb 3.6 V6 FSI,Hyderabad,2009,53000,Petrol,Automatic,First,0.0 kmpl,3597 CC,262.6 bhp,5.0,NaN,4.75,0,0,0,1
6012,6012,Toyota Innova 2.5 V Diesel 7-seater,Coimbatore,2011,45004,Diesel,Manual,First,12.8 kmpl,2494 CC,102 bhp,7.0,NaN,9.48,0,0,0,1
6013,6013,Honda Amaze VX i-DTEC,Coimbatore,2015,70602,Diesel,Manual,First,25.8 kmpl,1498 CC,98.6 bhp,5.0,NaN,4.83,0,0,0,1
6014,6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5.0,7.88 Lakh,4.75,0,0,0,1
6015,6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.4 kmpl,1120 CC,71 bhp,5.0,NaN,4.00,0,0,0,1
6016,6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.0 kmpl,2498 CC,112 bhp,8.0,NaN,2.90,2,0,0,2
6017,6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.9 kmpl,998 CC,67.1 bhp,5.0,NaN,2.65,0,0,0,1
6018,6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44 kmpl,936 CC,57.6 bhp,5.0,NaN,2.50,0,0,0,1

#### Codificación de frecuencias

In [16]:
df_train = pd.read_csv('C:/Users/HP/Downloads/train3.csv')
df_test = pd.read_csv('C:/Users/HP/Downloads/test3.csv')

In [17]:
freq = df_train['Owner_Type'].value_counts()
df_train['Owner_Type_fe'] = df_train['Owner_Type'].map(freq)
df_test['Owner_Type_fe'] = df_test['Owner_Type'].map(freq)

In [18]:
df_train.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Owner_Type_fe
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75,4929
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50,4929
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50,4929
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00,4929
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74,968

In [19]:
df_test.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Owner_Type_fe
0,0,Maruti Alto K10 LXI CNG,Delhi,2014,40929,CNG,Manual,First,32.26 km/kg,998 CC,58.2 bhp,4.0,NaN,4929
1,1,Maruti Alto 800 2016-2019 LXI,Coimbatore,2013,54493,Petrol,Manual,Second,24.7 kmpl,796 CC,47.3 bhp,5.0,NaN,968
2,2,Toyota Innova Crysta Touring Sport 2.4 MT,Mumbai,2017,34000,Diesel,Manual,First,13.68 kmpl,2393 CC,147.8 bhp,7.0,25.27 Lakh,4929
3,3,Toyota Etios Liva GD,Hyderabad,2012,139000,Diesel,Manual,First,23.59 kmpl,1364 CC,null bhp,5.0,NaN,4929
4,4,Hyundai i20 Magna,Mumbai,2014,29000,Petrol,Manual,First,18.5 kmpl,1197 CC,82.85 bhp,5.0,NaN,4929